### ISSUE TITLE
too many callbacks error

### ISSUE THREAD

**Issue by Bilebin** [LubinLew/lua-resty-hyperscan#1]
luajit throw "too many callbacks error" error when many requestes send

**Comment by LubinLew** [comment]
Thanks for reporting the issue.  I add a [wrapper](https://github.com/LubinLew/lua-resty-hyperscan/tree/main/hs_wrapper) to handle callbacks to solve this issue. 
Also, add [test cases](https://github.com/LubinLew/lua-resty-hyperscan/tree/main/t) for this project.
