### ISSUE TITLE
Failed to build hs_wrapper om ubuntu 18.04

### ISSUE THREAD

**Issue by DrPride** [LubinLew/lua-resty-hyperscan#2]
`gcc -shared  -Wl,--whole-archive -l:libhs.a -Wl,--no-whole-archive -o libwhs.so wrapper.o -lm -lstdc++ 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libhs.a(hs.cpp.o): relocation R_X86_64_PC32 against symbol _ZNSt8_Rb_treeIxSt4pairIKxjESt10_Select1stIS2_ESt4lessIxESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E' can not be used when making a shared object; recompile with -fPIC
`

**Comment by LubinLew** [comment]
You need to recompile hyperscan with `-fPIC` option. 

https://github.com/OpenSecHub/hyperscan-packaging/blob/main/rpm/hyperscan.spec#L69

**Comment by LubinLew** [comment]
@DrPride 

I changed the makefile, `libwhs.so` is no longer linking static hypersacn library, so you need to make sure `libhs.so` is installed in the system.

**Comment by DrPride** [comment]
Thanks, works for me.
